name: Check license

on: [ pull_request ]

jobs:
  licenseCheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'
    - name: Install addlicense
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        go get -v -u github.com/google/addlicense
    - name: Check license
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        addlicense -check -l apache -c "Amazon.com, Inc." $(find $PWD -type f -name "*.kt" -o -name "*.ts")

